### ISSUE TITLE
您是否试过使用Tobii Eye Tracker 5来进行眼动数据采集呢？

### ISSUE THREAD

**Issue by yuchen2199** [JamesQFreeman/MicEye#1]
非常棒的工作！感谢开源如此有用的数据采集工具。
但是我有一个疑问，您在论文里写到您使用的是tobii Eye Tracker 4C进行眼动数据采集，那您是否试过使用Tobii Eye Tracker 5来进行眼动数据采集呢？我想了解下使用Tobii Eye Tracker 5进行数据采集的可行性。

因为我在前期调研的时候，发现官方在Tobii5中没有提供有效的数据采集接口，仅是提供了unity环境下的数据采集SDK。所以我在看见您工作之前，一直认为Tobii5可能不能很好的支撑数据采集工作。

期待您的回复！谢谢！

**Comment by JamesQFreeman** [comment]
可以的呀，试试用C的API：https://github.com/JamesQFreeman/PyEyetracker
