### ISSUE TITLE
How to install TobiiEyeTracker module?

### ISSUE THREAD

**Issue by Franka-Med** [JamesQFreeman/MicEye#3]
When I run `python MicEye.py` after following the installation tutorial, I get ModuleNotFoundError: No module named 'TobiiEyeTracker'
I tried `pip install TobiiEyeTracker`, but it didn't work, where can I download this module?

**Comment by Fortogether** [comment]
Hi, I also encountered this problem, did you solve it and how did you solve it?

**Comment by Franka-Med** [comment]
@Fortogether Yes, I've solved the problem and it's working fine now. You can download it from this link corresponding DLL library: https://github.com/JamesQFreeman/PyEyetracker

**Comment by JamesQFreeman** [comment]
Thanks, I will link it down below the README.
